version: '3.1'
secrets:
    db_root_password:
        file: ./db_root_password
    db_user_password:
        file: ./db_user_password
services:
    helper:
        build: ./helper
        volumes:
            - ./database/initdb:/helper/initdb
    database:
        image: mariadb:10.2.9
        volumes:
            - ./database/initdb:/docker-entrypoint-initdb.d
        secrets:
            - db_root_password
            - db_user_password
        environment:
            - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
            - MYSQL_DATABASE=challenge
            - MYSQL_USER=challenge
            - MYSQL_PASSWORD_FILE=/run/secrets/db_user_password
        depends_on:
            - helper
